/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as TodayRouteImport } from './routes/today'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as QuranRouteImport } from './routes/quran'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GrammarRouteImport } from './routes/grammar'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as AlphabetRouteImport } from './routes/alphabet'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuranNumRouteImport } from './routes/quran.$num'

const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranRoute = QuranRouteImport.update({
  id: '/quran',
  path: '/quran',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarRoute = GrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const AlphabetRoute = AlphabetRouteImport.update({
  id: '/alphabet',
  path: '/alphabet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranNumRoute = QuranNumRouteImport.update({
  id: '/$num',
  path: '/$num',
  getParentRoute: () => QuranRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alphabet': typeof AlphabetRoute
  '/flashcards': typeof FlashcardsRoute
  '/grammar': typeof GrammarRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/quiz': typeof QuizRoute
  '/quran': typeof QuranRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/today': typeof TodayRoute
  '/vocabulary': typeof VocabularyRoute
  '/quran/$num': typeof QuranNumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alphabet': typeof AlphabetRoute
  '/flashcards': typeof FlashcardsRoute
  '/grammar': typeof GrammarRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/quiz': typeof QuizRoute
  '/quran': typeof QuranRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/today': typeof TodayRoute
  '/vocabulary': typeof VocabularyRoute
  '/quran/$num': typeof QuranNumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alphabet': typeof AlphabetRoute
  '/flashcards': typeof FlashcardsRoute
  '/grammar': typeof GrammarRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/quiz': typeof QuizRoute
  '/quran': typeof QuranRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/today': typeof TodayRoute
  '/vocabulary': typeof VocabularyRoute
  '/quran/$num': typeof QuranNumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alphabet'
    | '/flashcards'
    | '/grammar'
    | '/login'
    | '/progress'
    | '/quiz'
    | '/quran'
    | '/sitemap.xml'
    | '/today'
    | '/vocabulary'
    | '/quran/$num'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alphabet'
    | '/flashcards'
    | '/grammar'
    | '/login'
    | '/progress'
    | '/quiz'
    | '/quran'
    | '/sitemap.xml'
    | '/today'
    | '/vocabulary'
    | '/quran/$num'
  id:
    | '__root__'
    | '/'
    | '/alphabet'
    | '/flashcards'
    | '/grammar'
    | '/login'
    | '/progress'
    | '/quiz'
    | '/quran'
    | '/sitemap.xml'
    | '/today'
    | '/vocabulary'
    | '/quran/$num'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlphabetRoute: typeof AlphabetRoute
  FlashcardsRoute: typeof FlashcardsRoute
  GrammarRoute: typeof GrammarRoute
  LoginRoute: typeof LoginRoute
  ProgressRoute: typeof ProgressRoute
  QuizRoute: typeof QuizRoute
  QuranRoute: typeof QuranRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TodayRoute: typeof TodayRoute
  VocabularyRoute: typeof VocabularyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran': {
      id: '/quran'
      path: '/quran'
      fullPath: '/quran'
      preLoaderRoute: typeof QuranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar': {
      id: '/grammar'
      path: '/grammar'
      fullPath: '/grammar'
      preLoaderRoute: typeof GrammarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alphabet': {
      id: '/alphabet'
      path: '/alphabet'
      fullPath: '/alphabet'
      preLoaderRoute: typeof AlphabetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran/$num': {
      id: '/quran/$num'
      path: '/$num'
      fullPath: '/quran/$num'
      preLoaderRoute: typeof QuranNumRouteImport
      parentRoute: typeof QuranRoute
    }
  }
}

interface QuranRouteChildren {
  QuranNumRoute: typeof QuranNumRoute
}

const QuranRouteChildren: QuranRouteChildren = {
  QuranNumRoute: QuranNumRoute,
}

const QuranRouteWithChildren = QuranRoute._addFileChildren(QuranRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlphabetRoute: AlphabetRoute,
  FlashcardsRoute: FlashcardsRoute,
  GrammarRoute: GrammarRoute,
  LoginRoute: LoginRoute,
  ProgressRoute: ProgressRoute,
  QuizRoute: QuizRoute,
  QuranRoute: QuranRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TodayRoute: TodayRoute,
  VocabularyRoute: VocabularyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
